theme: jekyll-theme-minimal
#github: [metadata] 
repository: warrensbox/hubapp
logo: /assets/img/logo.png
title: hubapp

show_downloads: true

exclude: [vendor]

google_analytics: true

#github: [metadata] 
