theme: jekyll-theme-minimal
#github: [metadata] 
repository: warrensbox/github-appinstaller
logo: /assets/img/logo.png
title: appinstall

show_downloads: true

exclude: [vendor]

#github: [metadata] 
